<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Achievement;

class AchievementsSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing data
        Achievement::truncate();

        $achievements = [
            [
                'title' => 'Cimahi Motekar Award',
                'participant' => 'Raka Satria, Harits, Khalif, dan Daffa',
                'level' => 'Kabupaten/Kota',
                'rank' => 'Juara 2',
                'year' => '2023',
                'description' => 'Sistem Anti Kebakaran Berbasis Otomasi Software Engineering (SABOTASE) – penghargaan dari Pemerintah Kota Cimahi.',
            ],
            [
                'title' => 'Lomba Smart Student Patroli Keamanan Sekolah',
                'participant' => 'Zidane Yassid Rizqullah',
                'level' => 'Provinsi',
                'rank' => 'Juara Perintis 2',
                'year' => '2022',
                'description' => 'Kompetisi keamanan sekolah tingkat provinsi oleh POLDA Jawa Barat.',
            ],
            [
                'title' => 'LKS Teknik Desain Laman (Web Technologies)',
                'participant' => 'Muhammad Renaldy Ramadhan',
                'level' => 'Provinsi',
                'rank' => 'Juara 1',
                'year' => '2021',
                'description' => 'Juara 1 dalam lomba LKS bidang Web Technologies tingkat Jawa Barat.',
            ],
            [
                'title' => 'Widyatama Informatics Festival (WiFi) 2018 - Programming',
                'participant' => 'M. Seftikara, Afridho, Tommy',
                'level' => 'Provinsi',
                'rank' => 'Juara 1',
                'year' => '2018',
                'description' => 'Lomba programming tingkat provinsi di Universitas Widyatama.',
            ],
            [
                'title' => 'Widyatama Informatics Festival (WiFi) 2018 - Programming',
                'participant' => 'Aditya Galang, Harvan, Mus\'ab',
                'level' => 'Provinsi',
                'rank' => 'Juara 2',
                'year' => '2018',
                'description' => 'Juara 2 lomba programming tingkat provinsi di Universitas Widyatama.',
            ],
            [
                'title' => 'Widyatama Informatics Festival (WiFi) 2018 - Programming',
                'participant' => 'Julio, M. Fazri, Rizka Ghina',
                'level' => 'Provinsi',
                'rank' => 'Juara 3',
                'year' => '2018',
                'description' => 'Juara 3 lomba programming Universitas Widyatama.',
            ],
            [
                'title' => 'Widyatama Informatics Festival (WiFi) 2018 - Web Design',
                'participant' => 'Agista, Alvin, Moch Sultan',
                'level' => 'Provinsi',
                'rank' => 'Juara 3',
                'year' => '2018',
                'description' => 'Juara 3 bidang Web Design Universitas Widyatama.',
            ],
            [
                'title' => 'Web Design Widyatama Technology Event',
                'participant' => 'Agista',
                'level' => 'Provinsi',
                'rank' => 'Juara 1',
                'year' => '2018',
                'description' => 'Juara 1 lomba Web Design Widyatama Technology Event.',
            ],
            [
                'title' => 'Web Design Widyatama Technology Event',
                'participant' => 'Redi',
                'level' => 'Provinsi',
                'rank' => 'Juara 2',
                'year' => '2018',
                'description' => 'Juara 2 lomba Web Design Widyatama Technology Event.',
            ],
            [
                'title' => 'Widyatama Informatics Festival (WiFi) 2017 - Programming',
                'participant' => 'Suparlan, M Dhafin, Arip',
                'level' => 'Provinsi',
                'rank' => 'Juara 1',
                'year' => '2017',
                'description' => 'Juara 1 bidang Programming Universitas Widyatama.',
            ],
            [
                'title' => 'Widyatama Informatics Festival (WiFi) 2017 - Web Design',
                'participant' => 'Rizki Nino, Qolby',
                'level' => 'Provinsi',
                'rank' => 'Juara 1',
                'year' => '2017',
                'description' => 'Juara 1 bidang Web Design Universitas Widyatama.',
            ],
            [
                'title' => 'Web Design Competition Informatika UNJANI 2017',
                'participant' => 'Rizqi Nino, Mutiara Juanita',
                'level' => 'Kabupaten/Kota',
                'rank' => 'Juara 3',
                'year' => '2017',
                'description' => 'Juara 3 lomba Web Design di Universitas Jenderal Ahmad Yani.',
            ],
            [
                'title' => 'Lomba IT Kreatif 2017 Cimahi Apps Challenge',
                'participant' => 'Novianto & Ardiya',
                'level' => 'Nasional',
                'rank' => 'Juara 1',
                'year' => '2017',
                'description' => 'Sistem Emergency Cimahi (Sierri) – juara 1 tingkat nasional.',
            ],
            [
                'title' => 'Lomba Mobile Kihajar',
                'participant' => 'Adam Davarel',
                'level' => 'Nasional',
                'rank' => 'Juara 2',
                'year' => '2017',
                'description' => 'Lomba Mobile Kihajar oleh KEMDIKBUD.',
            ],
            [
                'title' => 'Musabaqoh Hifzil Qur\'an (MHQ)',
                'participant' => 'Siswa RPL',
                'level' => 'Kabupaten/Kota',
                'rank' => 'Juara 2',
                'year' => '2016',
                'description' => 'Kompetisi MHQ tingkat Bandung Raya.',
            ],
            [
                'title' => 'Lomba Cipta Karya Software (LCKS) Enumeration 2016',
                'participant' => 'M. Nasrulloh, Fathara dan Rifka',
                'level' => 'Nasional',
                'rank' => 'Finalis',
                'year' => '2016',
                'description' => 'Aplikasi Pencarian Rumah Sakit – lomba Enumeration PENS ITS Surabaya.',
            ],
            [
                'title' => 'Lomba IT Kreatif Cimahi Tahun 2016',
                'participant' => 'Farhan Rahmat Abdillah, Kiki Pratiwi, Lisna Dea D, Rizal Sidik',
                'level' => 'Kabupaten/Kota',
                'rank' => 'Juara 1',
                'year' => '2016',
                'description' => 'Aplikasi Rumah Sakit – Juara 1 tingkat Kota Cimahi.',
            ],
            [
                'title' => 'LKS IT Application',
                'participant' => 'M. Irfan Firdaus',
                'level' => 'Provinsi',
                'rank' => 'Juara 2',
                'year' => '2016',
                'description' => 'Juara 2 bidang IT Application tingkat Jawa Barat.',
            ],
            [
                'title' => 'Widyatama Informatics Festival (WiFi) 2016 - Web Design',
                'participant' => 'Gina Nabila, Faza Kamilah, Regita Lisgiani',
                'level' => 'Nasional',
                'rank' => 'Juara 1',
                'year' => '2016',
                'description' => 'Juara 1 Web Design tingkat nasional di Universitas Widyatama.',
            ],
            [
                'title' => 'Widyatama Informatics Festival (WiFi) 2016 - Web Design',
                'participant' => 'Melinia Nurfitri, Syifa Nurul, Venny Neviana',
                'level' => 'Nasional',
                'rank' => 'Juara 2',
                'year' => '2016',
                'description' => 'Juara 2 Web Design tingkat nasional di Universitas Widyatama.',
            ],
            [
                'title' => 'Widyatama Informatics Festival (WiFi) 2016 - Web Design',
                'participant' => 'Zulfa Nurul Azizah, Nisa Nurlita, Siti Fatimah',
                'level' => 'Nasional',
                'rank' => 'Juara 3',
                'year' => '2016',
                'description' => 'Juara 3 Web Design tingkat nasional Universitas Widyatama.',
            ],
            [
                'title' => 'Web Design Competition Telkom University 2016',
                'participant' => 'Irfan Fadillah, Dina Rahayu',
                'level' => 'Provinsi',
                'rank' => 'Juara 1',
                'year' => '2016',
                'description' => 'Lomba desain web yang diadakan oleh Telkom University Bandung.',
            ],
            [
                'title' => 'Mobile Apps Competition POLBAN',
                'participant' => 'Yoga Pratama dan Fadhil Rahman',
                'level' => 'Provinsi',
                'rank' => 'Juara 2',
                'year' => '2016',
                'description' => 'Lomba pengembangan aplikasi mobile tingkat Jawa Barat.',
            ],
            [
                'title' => 'LKS Software Application 2015',
                'participant' => 'M. Farhan Pratama',
                'level' => 'Kabupaten/Kota',
                'rank' => 'Juara 1',
                'year' => '2015',
                'description' => 'Juara 1 lomba keahlian software tingkat Kota Cimahi.',
            ],
            [
                'title' => 'LKS Web Design 2015',
                'participant' => 'Rizal Rahmadani',
                'level' => 'Provinsi',
                'rank' => 'Juara 2',
                'year' => '2015',
                'description' => 'Juara 2 lomba keahlian bidang Web Design tingkat Jawa Barat.',
            ],
            [
                'title' => 'LKS Nasional Software Application 2015',
                'participant' => 'Rizal Rahmadani',
                'level' => 'Nasional',
                'rank' => 'Finalis (Peringkat 5)',
                'year' => '2015',
                'description' => 'Finalis LKS Nasional bidang Software Application di Jakarta.',
            ],
            [
                'title' => 'App Innovation Challenge 2015',
                'participant' => 'Team Innovator RPL',
                'level' => 'Nasional',
                'rank' => 'Juara 1',
                'year' => '2015',
                'description' => 'Juara 1 lomba inovasi aplikasi tingkat nasional.',
            ],
            [
                'title' => 'Cimahi Smart City Hackathon',
                'participant' => 'Tim DevCimahi',
                'level' => 'Kabupaten/Kota',
                'rank' => 'Juara 1',
                'year' => '2015',
                'description' => 'Mengembangkan aplikasi "Cimahi Go Apps" untuk mendukung Smart City.',
            ],
            [
                'title' => 'Widyatama Informatics Festival 2015 - Programming',
                'participant' => 'Nur Alif, Rafiq, Ahmad Fauzi',
                'level' => 'Nasional',
                'rank' => 'Juara 1',
                'year' => '2015',
                'description' => 'Juara 1 Programming Competition WiFi 2015 Universitas Widyatama.',
            ],
            [
                'title' => 'Widyatama Informatics Festival 2015 - Web Design',
                'participant' => 'Aulia Rahma dan Nisa Khairani',
                'level' => 'Nasional',
                'rank' => 'Juara 2',
                'year' => '2015',
                'description' => 'Juara 2 Web Design WiFi 2015 Universitas Widyatama.',
            ],
            [
                'title' => 'National Software Competition 2014',
                'participant' => 'M. Rizqi Ramadhan',
                'level' => 'Nasional',
                'rank' => 'Juara 1',
                'year' => '2014',
                'description' => 'Juara 1 kompetisi software tingkat nasional di Universitas Telkom.',
            ],
            [
                'title' => 'LKS Kota Cimahi 2014',
                'participant' => 'M. Taufiqurrahman',
                'level' => 'Kabupaten/Kota',
                'rank' => 'Juara 1',
                'year' => '2014',
                'description' => 'Juara 1 LKS tingkat Kota Cimahi bidang RPL.',
            ],
            [
                'title' => 'LKS Provinsi Jawa Barat 2014',
                'participant' => 'M. Taufiqurrahman',
                'level' => 'Provinsi',
                'rank' => 'Juara 1',
                'year' => '2014',
                'description' => 'Juara 1 LKS bidang RPL tingkat Provinsi Jawa Barat.',
            ],
            [
                'title' => 'LKS Nasional 2014',
                'participant' => 'M. Taufiqurrahman',
                'level' => 'Nasional',
                'rank' => 'Juara 3',
                'year' => '2014',
                'description' => 'Juara 3 LKS Nasional bidang Rekayasa Perangkat Lunak.',
            ],
            [
                'title' => 'Festival TIK Bandung Raya',
                'participant' => 'Team Techno RPL',
                'level' => 'Kabupaten/Kota',
                'rank' => 'Juara 1',
                'year' => '2013',
                'description' => 'Festival TIK yang menampilkan inovasi aplikasi berbasis web.',
            ],
            [
                'title' => 'Smart City Innovation Challenge 2013',
                'participant' => 'Team DevCity',
                'level' => 'Kabupaten/Kota',
                'rank' => 'Juara 2',
                'year' => '2013',
                'description' => 'Inovasi sistem pelaporan publik berbasis web untuk Cimahi.',
            ],
            [
                'title' => 'LKS RPL 2013',
                'participant' => 'Bambang Setiawan',
                'level' => 'Kabupaten/Kota',
                'rank' => 'Juara 1',
                'year' => '2013',
                'description' => 'Juara 1 LKS bidang RPL tingkat Kota Cimahi.',
            ],
            [
                'title' => 'LKS Provinsi Jawa Barat 2013',
                'participant' => 'Bambang Setiawan',
                'level' => 'Provinsi',
                'rank' => 'Juara 2',
                'year' => '2013',
                'description' => 'Juara 2 LKS bidang RPL tingkat provinsi.',
            ],
            [
                'title' => 'Lomba Kihajar 2012',
                'participant' => 'Naufal Pradipta',
                'level' => 'Nasional',
                'rank' => 'Juara 3',
                'year' => '2012',
                'description' => 'Kompetisi konten edukatif Kihajar Kemendikbud.',
            ],
            [
                'title' => 'LKS Nasional 2012',
                'participant' => 'Asep Saepuloh',
                'level' => 'Nasional',
                'rank' => 'Juara 2',
                'year' => '2012',
                'description' => 'Juara 2 Lomba Kompetensi Siswa Nasional bidang RPL.',
            ],
            [
                'title' => 'Web Development Competition POLBAN',
                'participant' => 'Tim Kreatif RPL',
                'level' => 'Provinsi',
                'rank' => 'Juara 1',
                'year' => '2011',
                'description' => 'Juara 1 lomba Web Development di Politeknik Negeri Bandung.',
            ],
            [
                'title' => 'Mobile App Development Challenge',
                'participant' => 'Team Innovate',
                'level' => 'Provinsi',
                'rank' => 'Juara 2',
                'year' => '2011',
                'description' => 'Lomba pengembangan aplikasi Android tingkat Jawa Barat.',
            ],
            [
                'title' => 'Widyatama Informatics Festival 2011 - Programming',
                'participant' => 'Tim Alpha RPL',
                'level' => 'Nasional',
                'rank' => 'Juara 1',
                'year' => '2011',
                'description' => 'Juara 1 WiFi Competition bidang programming Universitas Widyatama.',
            ],
            [
                'title' => 'Widyatama Informatics Festival 2011 - Web Design',
                'participant' => 'Tim Beta RPL',
                'level' => 'Nasional',
                'rank' => 'Juara 2',
                'year' => '2011',
                'description' => 'Juara 2 Web Design WiFi 2011.',
            ],
            [
                'title' => 'Widyatama Informatics Festival 2011 - Web Design',
                'participant' => 'Tim Gamma RPL',
                'level' => 'Nasional',
                'rank' => 'Juara 3',
                'year' => '2011',
                'description' => 'Juara 3 Web Design WiFi 2011 Universitas Widyatama.',
            ],
            [
                'title' => 'LKS Kota Cimahi 2011',
                'participant' => 'Adi Santoso',
                'level' => 'Kabupaten/Kota',
                'rank' => 'Juara 1',
                'year' => '2011',
                'description' => 'Juara 1 LKS RPL tingkat Kota Cimahi.',
            ],
            [
                'title' => 'LKS Provinsi Jawa Barat 2011',
                'participant' => 'Adi Santoso',
                'level' => 'Provinsi',
                'rank' => 'Juara 2',
                'year' => '2011',
                'description' => 'Juara 2 LKS RPL tingkat Provinsi Jawa Barat.',
            ],
            [
                'title' => 'LKS Nasional 2011',
                'participant' => 'Adi Santoso',
                'level' => 'Nasional',
                'rank' => 'Finalis (Peringkat 4)',
                'year' => '2011',
                'description' => 'Finalis LKS Nasional bidang RPL.',
            ],
            [
                'title' => 'ICT Award Bandung 2010',
                'participant' => 'Team ICT RPL',
                'level' => 'Provinsi',
                'rank' => 'Juara 1',
                'year' => '2010',
                'description' => 'Juara 1 lomba ICT Award bidang Web Technology.',
            ],
            [
                'title' => 'LKS Provinsi Jawa Barat 2010',
                'participant' => 'M. Fadhlan',
                'level' => 'Provinsi',
                'rank' => 'Juara 2',
                'year' => '2010',
                'description' => 'Juara 2 LKS Provinsi bidang RPL.',
            ],
            [
                'title' => 'LKS Nasional 2010',
                'participant' => 'M. Fadhlan',
                'level' => 'Nasional',
                'rank' => 'Juara 3',
                'year' => '2010',
                'description' => 'Juara 3 Lomba Kompetensi Siswa Nasional bidang Rekayasa Perangkat Lunak.',
            ],
            [
                'title' => 'Lomba Web Design UNIKOM',
                'participant' => 'Tim UI/UX RPL',
                'level' => 'Provinsi',
                'rank' => 'Juara 1',
                'year' => '2009',
                'description' => 'Juara 1 lomba desain web Universitas Komputer Indonesia.',
            ],
            [
                'title' => 'LKS Kota Cimahi 2009',
                'participant' => 'Aji Maulana',
                'level' => 'Kabupaten/Kota',
                'rank' => 'Juara 1',
                'year' => '2009',
                'description' => 'Juara 1 LKS bidang Rekayasa Perangkat Lunak tingkat Kota Cimahi.',
            ],
            [
                'title' => 'LKS Provinsi Jawa Barat 2009',
                'participant' => 'Aji Maulana',
                'level' => 'Provinsi',
                'rank' => 'Juara 2',
                'year' => '2009',
                'description' => 'Juara 2 LKS bidang RPL tingkat Jawa Barat.',
            ],
            [
                'title' => 'LKS Nasional 2009',
                'participant' => 'Aji Maulana',
                'level' => 'Nasional',
                'rank' => 'Finalis',
                'year' => '2009',
                'description' => 'Finalis LKS Nasional bidang Rekayasa Perangkat Lunak.',
            ],
        ];

        foreach ($achievements as $achievement) {
            Achievement::create($achievement);
        }
    }
}
